update evaluation script

diff --git a/run-benchmark b/run-benchmark
--- a/run-benchmark
+++ b/run-benchmark
@@ -15,7 +15,7 @@ else
     source $VENV/bin/activate
 fi
 
-COMMANDS=(all ldbc10 pokec telecom ldbc01 leak paradise)
+COMMANDS=(all ldbc10 pokec telecom ldbc01 icijleak paradise)
 
 CMD=all
 if [[ ${1-} ]]; then
@@ -31,33 +31,34 @@ fi
 cmake -B build/Release -D CMAKE_BUILD_TYPE=Release
 cmake --build build/Release -j 15
 
-# Remove SPARQL tmp dir
-[[ -d  $TESTS/sparql/tmp/ ]] && echo -e ${BLUE}Removing  $TESTS/sparql/tmp/${NC} && rm -r  $TESTS/sparql/tmp/
+python3  $TESTS/script/evaluation.py $CMD | tee >(sed $'s/\033[[][^A-Za-z]*m//g' >  $TESTS/test-status-last.txt) || ERROR=true
+# # Remove SPARQL tmp dir
+# [[ -d  $TESTS/sparql/tmp/ ]] && echo -e ${BLUE}Removing  $TESTS/sparql/tmp/${NC} && rm -r  $TESTS/sparql/tmp/
 
-# Remove MQL tmp dir
-[[ -d  $TESTS/mql/tmp/ ]] && echo -e ${BLUE}Removing  $TESTS/mql/tmp/${NC} && rm -r  $TESTS/mql/tmp/
+# # Remove MQL tmp dir
+# [[ -d  $TESTS/mql/tmp/ ]] && echo -e ${BLUE}Removing  $TESTS/mql/tmp/${NC} && rm -r  $TESTS/mql/tmp/
 
 
-if [[ $CMD = "all" || $CMD = "sparql" ]]; then
-    printf "${BLUE}RUNNING SPARQL INTEGRATION TESTS${NC}\n"
-    python3  $TESTS/sparql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' >  $TESTS/sparql/test-status-last.txt) || ERROR=true
-fi
+# if [[ $CMD = "all" || $CMD = "sparql" ]]; then
+#     printf "${BLUE}RUNNING SPARQL INTEGRATION TESTS${NC}\n"
+#     python3  $TESTS/sparql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' >  $TESTS/sparql/test-status-last.txt) || ERROR=true
+# fi
 
-if [[ $CMD = "all" || $CMD = "mql" ]]; then
-    printf "${BLUE}RUNNING MQL INTEGRATION TESTS${NC}\n"
-    python3  $TESTS/mql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' >  $TESTS/mql/test-status-last.txt) || ERROR=true
-fi
+# if [[ $CMD = "all" || $CMD = "mql" ]]; then
+#     printf "${BLUE}RUNNING MQL INTEGRATION TESTS${NC}\n"
+#     python3  $TESTS/mql/scripts/test.py | tee >(sed $'s/\033[[][^A-Za-z]*m//g' >  $TESTS/mql/test-status-last.txt) || ERROR=true
+# fi
 
-if [[ $CMD = "all" || $CMD = "unit" ]]; then
-    cd build/Debug/
-    printf "${BLUE}RUNNING UNIT TESTS${NC}\n"
-    ctest --output-on-failure || ERROR=true
-fi
+# if [[ $CMD = "all" || $CMD = "unit" ]]; then
+#     cd build/Debug/
+#     printf "${BLUE}RUNNING UNIT TESTS${NC}\n"
+#     ctest --output-on-failure || ERROR=true
+# fi
 
-if [[ $ERROR ]]; then
-    echo -e "${RED}TESTS FAILED${NC}"
-    exit 1
-else
-    echo -e "${GREEN}ALL TESTS PASSED${NC}"
-    exit 0
-fi
+# if [[ $ERROR ]]; then
+#     echo -e "${RED}TESTS FAILED${NC}"
+#     exit 1
+# else
+#     echo -e "${GREEN}ALL TESTS PASSED${NC}"
+#     exit 0
+# fi
